adjectivesList = [ 
    "smelly", 
    "dumb", 
    "moist", 
    "wet", 
    "mouldy", 
    "dehydrated watermelon",
    "pompous", 
    "eletist", 
    "capitalist", 
    "communist",
    "cringe",
    "truculent",
    "fatuous",
    "vainglorious",
    "fatuous",
    "petulant",
    "moribund",
    "jejune",
    "feckless",
    "antiquated",
    "rambunctious",
    "mundane",
    "misshapen",
    "glib",
    "dreary",
    "dopey",
    "devoid", 
    "deleterious",
    "degrading",
    "clammy",
    "brazen",
    "indiscreet",
    "indecorous",
    "imbecilic",
    "dysfunctional",
    "dubious",
    "drunken",
    "disreputable",
    "dismal",
    "dim",
    "deficient",
    "deceitful",
    "damned",
    "daft",
    "contrary",
    "churlish",
    "catty",
    "banal",
    "asinine",
    "infantile", 
    "lurid",
    "morbid",
    "repugnant",
    "unkempt",
    "vapid",
    "decrepit",
    "malevolent",
    "impertinent",
    "decrepit",
    "grotesque",
    "puerile",

]

short = [
    "dwarf",
    "goblin",
    "gremlin",
    "nae nae baby",
    "chihuahua",
    "gnome",

]